# Generated by Django 3.0.8 on 2020-07-31 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200731_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
